services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5446:5432"
    volumes:
      - haribahagia_data:/var/lib/postgresql/data

volumes:
  haribahagia_data:
