/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationsNewRouteImport } from './routes/invitations/new'
import { Route as InvitationsInvitationIdRouteRouteImport } from './routes/invitations/$invitationId/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsNewRoute = InvitationsNewRouteImport.update({
  id: '/invitations/new',
  path: '/invitations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsInvitationIdRouteRoute =
  InvitationsInvitationIdRouteRouteImport.update({
    id: '/invitations/$invitationId',
    path: '/invitations/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRouteRoute
  '/invitations/new': typeof InvitationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRouteRoute
  '/invitations/new': typeof InvitationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRouteRoute
  '/invitations/new': typeof InvitationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invitations/$invitationId' | '/invitations/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invitations/$invitationId' | '/invitations/new'
  id: '__root__' | '/' | '/invitations/$invitationId' | '/invitations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitationsInvitationIdRouteRoute: typeof InvitationsInvitationIdRouteRoute
  InvitationsNewRoute: typeof InvitationsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/new': {
      id: '/invitations/new'
      path: '/invitations/new'
      fullPath: '/invitations/new'
      preLoaderRoute: typeof InvitationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$invitationId': {
      id: '/invitations/$invitationId'
      path: '/invitations/$invitationId'
      fullPath: '/invitations/$invitationId'
      preLoaderRoute: typeof InvitationsInvitationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitationsInvitationIdRouteRoute: InvitationsInvitationIdRouteRoute,
  InvitationsNewRoute: InvitationsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
